# FEVER Exploration

This notebook is for quick sanity checks after Phase 2.

Goals:
- load processed FEVER claims/evidence parquet files
- inspect schema and counts
- view sample claims
- view sample evidence
- inspect one SUPPORTS claim
- inspect one REFUTES claim
- confirm processed outputs look correct

In [1]:
from pathlib import Path

import pandas as pd

In [2]:
CLAIMS_PATH = Path("../data/processed/fever_claims.parquet")
EVIDENCE_PATH = Path("../data/processed/fever_evidence.parquet")

CLAIMS_SAMPLE_PATH = Path("../data/processed/fever_claims_sample.parquet")
EVIDENCE_SAMPLE_PATH = Path("../data/processed/fever_evidence_sample.parquet")

In [3]:
claims_df = pd.read_parquet(CLAIMS_PATH)
evidence_df = pd.read_parquet(EVIDENCE_PATH)

claims_sample_df = pd.read_parquet(CLAIMS_SAMPLE_PATH)
evidence_sample_df = pd.read_parquet(EVIDENCE_SAMPLE_PATH)

print("claims_df shape:", claims_df.shape)
print("evidence_df shape:", evidence_df.shape)
print("claims_sample_df shape:", claims_sample_df.shape)
print("evidence_sample_df shape:", evidence_sample_df.shape)

claims_df shape: (165447, 7)
evidence_df shape: (348997, 13)
claims_sample_df shape: (200, 7)
evidence_sample_df shape: (380, 13)

In [4]:
print("Claims columns:")
print(claims_df.columns.tolist())

print("\nEvidence columns:")
print(evidence_df.columns.tolist())

Claims columns:
['claim_id', 'split', 'claim_text', 'claim_text_normalized', 'label', 'verifiable', 'num_evidence_sets']

Evidence columns:
['claim_id', 'split', 'claim_text', 'claim_text_normalized', 'label', 'verifiable', 'evidence_set_index', 'evidence_item_index', 'annotation_id', 'evidence_id', 'page_title', 'sentence_id', 'has_concrete_evidence']

In [5]:
claims_df.head(10)

,claim_id,split,claim_text,claim_text_normalized,label,verifiable,num_evidence_sets
0,75397,train,Nikolaj Coster-Waldau worked with the Fox Broa...,Nikolaj Coster-Waldau worked with the Fox Broa...,SUPPORTS,VERIFIABLE,1
1,150448,train,Roman Atwood is a content creator.,Roman Atwood is a content creator.,SUPPORTS,VERIFIABLE,2
2,214861,train,"History of art includes architecture, dance, s...","History of art includes architecture, dance, s...",SUPPORTS,VERIFIABLE,1
3,156709,train,Adrienne Bailon is an accountant.,Adrienne Bailon is an accountant.,REFUTES,VERIFIABLE,1
4,83235,train,System of a Down briefly disbanded in limbo.,System of a Down briefly disbanded in limbo.,NOT ENOUGH INFO,NOT VERIFIABLE,1
5,129629,train,Homeland is an American television spy thrille...,Homeland is an American television spy thrille...,SUPPORTS,VERIFIABLE,1
6,149579,train,Beautiful reached number two on the Billboard ...,Beautiful reached number two on the Billboard ...,NOT ENOUGH INFO,NOT VERIFIABLE,1
7,229289,train,Neal Schon was named in 1954.,Neal Schon was named in 1954.,NOT ENOUGH INFO,NOT VERIFIABLE,1
8,33078,train,The Boston Celtics play their home games at TD...,The Boston Celtics play their home games at TD...,SUPPORTS,VERIFIABLE,2
9,6744,train,The Ten Commandments is an epic film.,The Ten Commandments is an epic film.,SUPPORTS,VERIFIABLE,2

In [6]:
evidence_df.head(10)

,claim_id,split,claim_text,claim_text_normalized,label,verifiable,evidence_set_index,evidence_item_index,annotation_id,evidence_id,page_title,sentence_id,has_concrete_evidence
0,75397,train,Nikolaj Coster-Waldau worked with the Fox Broa...,Nikolaj Coster-Waldau worked with the Fox Broa...,SUPPORTS,VERIFIABLE,0,0,92206,104971.0,Nikolaj_Coster-Waldau,7.0,True
1,75397,train,Nikolaj Coster-Waldau worked with the Fox Broa...,Nikolaj Coster-Waldau worked with the Fox Broa...,SUPPORTS,VERIFIABLE,0,1,92206,104971.0,Fox_Broadcasting_Company,0.0,True
2,150448,train,Roman Atwood is a content creator.,Roman Atwood is a content creator.,SUPPORTS,VERIFIABLE,0,0,174271,187498.0,Roman_Atwood,1.0,True
3,150448,train,Roman Atwood is a content creator.,Roman Atwood is a content creator.,SUPPORTS,VERIFIABLE,1,0,174271,187499.0,Roman_Atwood,3.0,True
4,214861,train,"History of art includes architecture, dance, s...","History of art includes architecture, dance, s...",SUPPORTS,VERIFIABLE,0,0,255136,254645.0,History_of_art,2.0,True
5,156709,train,Adrienne Bailon is an accountant.,Adrienne Bailon is an accountant.,REFUTES,VERIFIABLE,0,0,180804,193183.0,Adrienne_Bailon,0.0,True
6,83235,train,System of a Down briefly disbanded in limbo.,System of a Down briefly disbanded in limbo.,NOT ENOUGH INFO,NOT VERIFIABLE,0,0,100277,NaN,NaN,NaN,False
7,129629,train,Homeland is an American television spy thrille...,Homeland is an American television spy thrille...,SUPPORTS,VERIFIABLE,0,0,151831,166598.0,Homeland_-LRB-TV_series-RRB-,0.0,True
8,129629,train,Homeland is an American television spy thrille...,Homeland is an American television spy thrille...,SUPPORTS,VERIFIABLE,0,1,151831,166598.0,Prisoners_of_War_-LRB-TV_series-RRB-,0.0,True
9,149579,train,Beautiful reached number two on the Billboard ...,Beautiful reached number two on the Billboard ...,NOT ENOUGH INFO,NOT VERIFIABLE,0,0,173384,NaN,NaN,NaN,False

In [7]:
claims_df["split"].value_counts(dropna=False)

split
train    145449
dev        9999
test       9999
Name: count, dtype: int64

In [8]:
claims_df["label"].value_counts(dropna=False)

label
SUPPORTS           86701
NOT ENOUGH INFO    42305
REFUTES            36441
Name: count, dtype: int64

In [9]:
claims_df["verifiable"].value_counts(dropna=False)

verifiable
VERIFIABLE        123142
NOT VERIFIABLE     42305
Name: count, dtype: int64

In [10]:
claims_df["claim_text_normalized"].isna().sum()

np.int64(0)

In [11]:
claims_df["claim_text_normalized"].dropna().head(10).tolist()

['Nikolaj Coster-Waldau worked with the Fox Broadcasting Company.',
 'Roman Atwood is a content creator.',
 'History of art includes architecture, dance, sculpture, music, painting, poetry literature, theatre, narrative, film, photography and graphic arts.',
 'Adrienne Bailon is an accountant.',
 'System of a Down briefly disbanded in limbo.',
 'Homeland is an American television spy thriller based on the Israeli television series Prisoners of War.',
 'Beautiful reached number two on the Billboard Hot 100 in 2003.',
 'Neal Schon was named in 1954.',
 'The Boston Celtics play their home games at TD Garden.',
 'The Ten Commandments is an epic film.']

In [12]:
print("Concrete evidence rows:", int(evidence_df["has_concrete_evidence"].sum()))
print("Null page_title rows:", int(evidence_df["page_title"].isna().sum()))
print("Null sentence_id rows:", int(evidence_df["sentence_id"].isna().sum()))

Concrete evidence rows: 292447
Null page_title rows: 56550
Null sentence_id rows: 56550

Sample SUPPORTS evidence rows

In [13]:
supports_rows = evidence_df[evidence_df["label"] == "SUPPORTS"]
supports_rows.head(10)

,claim_id,split,claim_text,claim_text_normalized,label,verifiable,evidence_set_index,evidence_item_index,annotation_id,evidence_id,page_title,sentence_id,has_concrete_evidence
0,75397,train,Nikolaj Coster-Waldau worked with the Fox Broa...,Nikolaj Coster-Waldau worked with the Fox Broa...,SUPPORTS,VERIFIABLE,0,0,92206,104971.0,Nikolaj_Coster-Waldau,7.0,True
1,75397,train,Nikolaj Coster-Waldau worked with the Fox Broa...,Nikolaj Coster-Waldau worked with the Fox Broa...,SUPPORTS,VERIFIABLE,0,1,92206,104971.0,Fox_Broadcasting_Company,0.0,True
2,150448,train,Roman Atwood is a content creator.,Roman Atwood is a content creator.,SUPPORTS,VERIFIABLE,0,0,174271,187498.0,Roman_Atwood,1.0,True
3,150448,train,Roman Atwood is a content creator.,Roman Atwood is a content creator.,SUPPORTS,VERIFIABLE,1,0,174271,187499.0,Roman_Atwood,3.0,True
4,214861,train,"History of art includes architecture, dance, s...","History of art includes architecture, dance, s...",SUPPORTS,VERIFIABLE,0,0,255136,254645.0,History_of_art,2.0,True
7,129629,train,Homeland is an American television spy thrille...,Homeland is an American television spy thrille...,SUPPORTS,VERIFIABLE,0,0,151831,166598.0,Homeland_-LRB-TV_series-RRB-,0.0,True
8,129629,train,Homeland is an American television spy thrille...,Homeland is an American television spy thrille...,SUPPORTS,VERIFIABLE,0,1,151831,166598.0,Prisoners_of_War_-LRB-TV_series-RRB-,0.0,True
11,33078,train,The Boston Celtics play their home games at TD...,The Boston Celtics play their home games at TD...,SUPPORTS,VERIFIABLE,0,0,49158,58489.0,Boston_Celtics,3.0,True
12,33078,train,The Boston Celtics play their home games at TD...,The Boston Celtics play their home games at TD...,SUPPORTS,VERIFIABLE,1,0,49159,58490.0,Boston_Celtics,3.0,True
13,6744,train,The Ten Commandments is an epic film.,The Ten Commandments is an epic film.,SUPPORTS,VERIFIABLE,0,0,23513,28977.0,The_Ten_Commandments_-LRB-1956_film-RRB-,0.0,True

Sample REFUTES evidence rows

In [14]:
refutes_rows = evidence_df[evidence_df["label"] == "REFUTES"]
refutes_rows.head(10)

,claim_id,split,claim_text,claim_text_normalized,label,verifiable,evidence_set_index,evidence_item_index,annotation_id,evidence_id,page_title,sentence_id,has_concrete_evidence
5,156709,train,Adrienne Bailon is an accountant.,Adrienne Bailon is an accountant.,REFUTES,VERIFIABLE,0,0,180804,193183.0,Adrienne_Bailon,0.0,True
23,138503,train,"Stranger Things is set in Bloomington, Indiana.","Stranger Things is set in Bloomington, Indiana.",REFUTES,VERIFIABLE,0,0,161295,175782.0,Stranger_Things,5.0,True
28,73170,train,Puerto Rico is not an unincorporated territory...,Puerto Rico is not an unincorporated territory...,REFUTES,VERIFIABLE,0,0,89957,102650.0,Puerto_Rico,0.0,True
54,15812,train,Peggy Sue Got Married is a Egyptian film relea...,Peggy Sue Got Married is a Egyptian film relea...,REFUTES,VERIFIABLE,0,0,31205,37902.0,Peggy_Sue_Got_Married,0.0,True
55,15812,train,Peggy Sue Got Married is a Egyptian film relea...,Peggy Sue Got Married is a Egyptian film relea...,REFUTES,VERIFIABLE,0,1,31205,37902.0,Francis_Ford_Coppola,0.0,True
56,15812,train,Peggy Sue Got Married is a Egyptian film relea...,Peggy Sue Got Married is a Egyptian film relea...,REFUTES,VERIFIABLE,1,0,31211,37908.0,Peggy_Sue_Got_Married,0.0,True
57,57330,train,Andy Roddick lost 5 Master Series between 2002...,Andy Roddick lost 5 Master Series between 2002...,REFUTES,VERIFIABLE,0,0,73660,84912.0,Andy_Roddick,7.0,True
58,52432,train,"As the Vietnam War raged in 1969, Yoko Ono and...","As the Vietnam War raged in 1969, Yoko Ono and...",REFUTES,VERIFIABLE,0,0,68739,79581.0,Bed-In,0.0,True
75,180769,train,Grace Jones is a dancer.,Grace Jones is a dancer.,REFUTES,VERIFIABLE,0,0,209812,217612.0,Grace_Jones,0.0,True
78,111602,train,Willie Nelson dropped out of college after thr...,Willie Nelson dropped out of college after thr...,REFUTES,VERIFIABLE,0,0,131008,145780.0,Willie_Nelson,9.0,True

Inspect one SUPPORTS claim with its evidence rows

In [15]:
support_claim_id = supports_rows.iloc[0]["claim_id"]
support_claim = claims_df[claims_df["claim_id"] == support_claim_id]
support_evidence = evidence_df[evidence_df["claim_id"] == support_claim_id]

print("SUPPORT CLAIM")
display(support_claim)

print("\nSUPPORT EVIDENCE")
display(support_evidence)

SUPPORT CLAIM

,claim_id,split,claim_text,claim_text_normalized,label,verifiable,num_evidence_sets
0,75397,train,Nikolaj Coster-Waldau worked with the Fox Broa...,Nikolaj Coster-Waldau worked with the Fox Broa...,SUPPORTS,VERIFIABLE,1

SUPPORT EVIDENCE

,claim_id,split,claim_text,claim_text_normalized,label,verifiable,evidence_set_index,evidence_item_index,annotation_id,evidence_id,page_title,sentence_id,has_concrete_evidence
0,75397,train,Nikolaj Coster-Waldau worked with the Fox Broa...,Nikolaj Coster-Waldau worked with the Fox Broa...,SUPPORTS,VERIFIABLE,0,0,92206,104971.0,Nikolaj_Coster-Waldau,7.0,True
1,75397,train,Nikolaj Coster-Waldau worked with the Fox Broa...,Nikolaj Coster-Waldau worked with the Fox Broa...,SUPPORTS,VERIFIABLE,0,1,92206,104971.0,Fox_Broadcasting_Company,0.0,True

Inspect one REFUTES claim with its evidence rows

In [16]:
refute_claim_id = refutes_rows.iloc[0]["claim_id"]
refute_claim = claims_df[claims_df["claim_id"] == refute_claim_id]
refute_evidence = evidence_df[evidence_df["claim_id"] == refute_claim_id]

print("REFUTE CLAIM")
display(refute_claim)

print("\nREFUTE EVIDENCE")
display(refute_evidence)

REFUTE CLAIM

,claim_id,split,claim_text,claim_text_normalized,label,verifiable,num_evidence_sets
3,156709,train,Adrienne Bailon is an accountant.,Adrienne Bailon is an accountant.,REFUTES,VERIFIABLE,1

REFUTE EVIDENCE

,claim_id,split,claim_text,claim_text_normalized,label,verifiable,evidence_set_index,evidence_item_index,annotation_id,evidence_id,page_title,sentence_id,has_concrete_evidence
5,156709,train,Adrienne Bailon is an accountant.,Adrienne Bailon is an accountant.,REFUTES,VERIFIABLE,0,0,180804,193183.0,Adrienne_Bailon,0.0,True

Inspect one NOT ENOUGH INFO claim

In [17]:
nei_rows = evidence_df[evidence_df["label"] == "NOT ENOUGH INFO"]
nei_rows.head(10)

,claim_id,split,claim_text,claim_text_normalized,label,verifiable,evidence_set_index,evidence_item_index,annotation_id,evidence_id,page_title,sentence_id,has_concrete_evidence
6,83235,train,System of a Down briefly disbanded in limbo.,System of a Down briefly disbanded in limbo.,NOT ENOUGH INFO,NOT VERIFIABLE,0,0,100277,NaN,NaN,NaN,False
9,149579,train,Beautiful reached number two on the Billboard ...,Beautiful reached number two on the Billboard ...,NOT ENOUGH INFO,NOT VERIFIABLE,0,0,173384,NaN,NaN,NaN,False
10,229289,train,Neal Schon was named in 1954.,Neal Schon was named in 1954.,NOT ENOUGH INFO,NOT VERIFIABLE,0,0,273626,NaN,NaN,NaN,False
48,138117,train,John Wick: Chapter 2 was theatrically released...,John Wick: Chapter 2 was theatrically released...,NOT ENOUGH INFO,NOT VERIFIABLE,0,0,160895,NaN,NaN,NaN,False
50,210010,train,Afghanistan is the source of the Kushan dynasty.,Afghanistan is the source of the Kushan dynasty.,NOT ENOUGH INFO,NOT VERIFIABLE,0,0,248748,NaN,NaN,NaN,False
51,134381,train,Marilyn Monroe worked with Warner Brothers.,Marilyn Monroe worked with Warner Brothers.,NOT ENOUGH INFO,NOT VERIFIABLE,0,0,156940,NaN,NaN,NaN,False
61,228761,train,Harold Ramis was a veteran.,Harold Ramis was a veteran.,NOT ENOUGH INFO,NOT VERIFIABLE,0,0,272943,NaN,NaN,NaN,False
63,85441,train,United Nations was relocated to the United Sta...,United Nations was relocated to the United Sta...,NOT ENOUGH INFO,NOT VERIFIABLE,0,0,102619,NaN,NaN,NaN,False
64,65960,train,Whoopi Goldberg co-produced an American dance ...,Whoopi Goldberg co-produced an American dance ...,NOT ENOUGH INFO,NOT VERIFIABLE,0,0,82524,NaN,NaN,NaN,False
68,56204,train,Keith Urban is a person who sings.,Keith Urban is a person who sings.,NOT ENOUGH INFO,NOT VERIFIABLE,0,0,176603,NaN,NaN,NaN,False

In [18]:
nei_claim_id = nei_rows.iloc[0]["claim_id"]
nei_claim = claims_df[claims_df["claim_id"] == nei_claim_id]
nei_evidence = evidence_df[evidence_df["claim_id"] == nei_claim_id]

print("NEI CLAIM")
display(nei_claim)

print("\nNEI EVIDENCE")
display(nei_evidence)

NEI CLAIM

,claim_id,split,claim_text,claim_text_normalized,label,verifiable,num_evidence_sets
4,83235,train,System of a Down briefly disbanded in limbo.,System of a Down briefly disbanded in limbo.,NOT ENOUGH INFO,NOT VERIFIABLE,1

NEI EVIDENCE

,claim_id,split,claim_text,claim_text_normalized,label,verifiable,evidence_set_index,evidence_item_index,annotation_id,evidence_id,page_title,sentence_id,has_concrete_evidence
6,83235,train,System of a Down briefly disbanded in limbo.,System of a Down briefly disbanded in limbo.,NOT ENOUGH INFO,NOT VERIFIABLE,0,0,100277,NaN,NaN,NaN,False

In [19]:
print("Unique claim_ids in claims_df:", claims_df["claim_id"].nunique())
print("Unique claim_ids in evidence_df:", evidence_df["claim_id"].nunique())

Unique claim_ids in claims_df: 165447
Unique claim_ids in evidence_df: 165447

In [20]:
print("Sample claims:")
display(claims_sample_df.head())

print("\nSample evidence:")
display(evidence_sample_df.head())

Sample claims:

,claim_id,split,claim_text,claim_text_normalized,label,verifiable,num_evidence_sets
0,59999,train,Prison Break was not created by Paul Scheuring.,Prison Break was not created by Paul Scheuring.,REFUTES,VERIFIABLE,3
1,88304,train,Jacqueline Kennedy Onassis was famous.,Jacqueline Kennedy Onassis was famous.,SUPPORTS,VERIFIABLE,4
2,74179,train,Toyota is an automobile company.,Toyota is an automobile company.,SUPPORTS,VERIFIABLE,1
3,199984,train,Mel Gibson studied in a national education and...,Mel Gibson studied in a national education and...,NOT ENOUGH INFO,NOT VERIFIABLE,1
4,28022,train,"Tyler, The Creator was born Tyler Gregory Okonma.","Tyler, The Creator was born Tyler Gregory Okonma.",SUPPORTS,VERIFIABLE,1

Sample evidence:

,claim_id,split,claim_text,claim_text_normalized,label,verifiable,evidence_set_index,evidence_item_index,annotation_id,evidence_id,page_title,sentence_id,has_concrete_evidence
0,200996,train,Iowa is a part of the Midwestern United States.,Iowa is a part of the Midwestern United States.,SUPPORTS,VERIFIABLE,0,0,236500,238958.0,Midwestern_United_States,4.0,True
1,23265,train,Peyton Manning played for the Colts.,Peyton Manning played for the Colts.,SUPPORTS,VERIFIABLE,0,0,39228,47246.0,Peyton_Manning,0.0,True
2,23265,train,Peyton Manning played for the Colts.,Peyton Manning played for the Colts.,SUPPORTS,VERIFIABLE,1,0,39228,47247.0,Peyton_Manning,1.0,True
3,23265,train,Peyton Manning played for the Colts.,Peyton Manning played for the Colts.,SUPPORTS,VERIFIABLE,2,0,39228,47248.0,Peyton_Manning,6.0,True
4,23265,train,Peyton Manning played for the Colts.,Peyton Manning played for the Colts.,SUPPORTS,VERIFIABLE,3,0,39228,47249.0,Peyton_Manning,7.0,True

Useful debugging query by claim id

In [21]:
def inspect_claim(claim_id: int):
    claim_row = claims_df[claims_df["claim_id"] == claim_id]
    evidence_rows = evidence_df[evidence_df["claim_id"] == claim_id]

    print("CLAIM ROW")
    display(claim_row)

    print("\nEVIDENCE ROWS")
    display(evidence_rows)

In [22]:
inspect_claim(75397)

CLAIM ROW

,claim_id,split,claim_text,claim_text_normalized,label,verifiable,num_evidence_sets
0,75397,train,Nikolaj Coster-Waldau worked with the Fox Broa...,Nikolaj Coster-Waldau worked with the Fox Broa...,SUPPORTS,VERIFIABLE,1

EVIDENCE ROWS

,claim_id,split,claim_text,claim_text_normalized,label,verifiable,evidence_set_index,evidence_item_index,annotation_id,evidence_id,page_title,sentence_id,has_concrete_evidence
0,75397,train,Nikolaj Coster-Waldau worked with the Fox Broa...,Nikolaj Coster-Waldau worked with the Fox Broa...,SUPPORTS,VERIFIABLE,0,0,92206,104971.0,Nikolaj_Coster-Waldau,7.0,True
1,75397,train,Nikolaj Coster-Waldau worked with the Fox Broa...,Nikolaj Coster-Waldau worked with the Fox Broa...,SUPPORTS,VERIFIABLE,0,1,92206,104971.0,Fox_Broadcasting_Company,0.0,True

## Phase 2 sanity checklist

- processed parquet files load successfully
- splits look correct
- labels look correct
- normalized claim text exists
- evidence rows flatten correctly
- sample claim inspection works

If all checks pass, Phase 2 is healthy.